import Cocoa

// MARK: - Protocols

protocol PasteboardReading: AnyObject {
    var changeCount: Int { get }

    /// Reads whatever is currently on the pasteboard as a `ClipboardItem`.
    /// Returns nil when the content is marked (password managers set
    /// concealed/transient/auto-generated types); when the pasteboard
    /// offers an image flavor (`.png` or `.tiff`) but the image is
    /// oversized or fails to decode — an image never falls back to text,
    /// it is skipped outright; or when there is no image flavor and no
    /// `.string` either (or the string is empty).
    func readCurrentItem(now: Date) -> ClipboardItem?
}

protocol PasteboardWriting: AnyObject {
    /// Writes `item` to the pasteboard and returns the change count the
    /// write itself produced, so the caller can adopt that value directly
    /// as its new baseline instead of reading `changeCount` back out right
    /// after — a gap in which a third-party copy could land and be
    /// mistaken for our own write. Not `@discardableResult`: discarding it
    /// silently is exactly the bug this return value exists to prevent.
    func write(_ item: ClipboardItem, withFormatting: Bool) -> Int
}

protocol KeystrokeSending {
    func sendPasteKeystroke()
}

// MARK: - SystemPasteboard

/// Adapts `NSPasteboard.general` to `PasteboardReading`/`PasteboardWriting`.
final class SystemPasteboard: PasteboardReading, PasteboardWriting {
    /// Types apps (mainly password managers) set to opt content out of
    /// clipboard managers. See https://nspasteboard.org.
    private static let markerTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private let pasteboard = NSPasteboard.general

    var changeCount: Int { pasteboard.changeCount }

    func readCurrentItem(now: Date) -> ClipboardItem? {
        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.markerTypes) else { return nil }

        // Decide the flavor from the advertised types, not from whether a
        // read happens to succeed: an image flavor that turns out
        // oversized or undecodable is a skip, not a reason to fall
        // through and read it as text.
        if types.contains(.png) || types.contains(.tiff) {
            return readImage(now: now)
        }
        return readText(now: now)
    }

    /// `clearContents()` both establishes this pasteboard as the new owner
    /// and returns the resulting change count; the `setString`/`setData`
    /// calls below write flavors onto that same owner without bumping the
    /// count any further, so that returned value is exactly what the next
    /// `changeCount` read would report.
    func write(_ item: ClipboardItem, withFormatting: Bool) -> Int {
        let newChangeCount = pasteboard.clearContents()
        switch item.kind {
        case .text(let plain, let rtf, let html):
            writeText(plain: plain, rtf: rtf, html: html, withFormatting: withFormatting)
        case .image(let png, _):
            writeImage(png: png)
        }
        return newChangeCount
    }

    // MARK: Reading

    /// Only called when the pasteboard's types include `.png` or `.tiff`.
    /// Reads `.png` data if present, otherwise `.tiff` data re-encoded to
    /// PNG. Either way the pixel size comes from the decoded bitmap, not
    /// point size. Returns nil — not a fallback to text — when the image
    /// is over `ClipboardHistory.maxItemBytes` or fails to decode.
    private func readImage(now: Date) -> ClipboardItem? {
        let png: Data
        let bitmap: NSBitmapImageRep

        if let pngData = pasteboard.data(forType: .png), let rep = NSBitmapImageRep(data: pngData) {
            png = pngData
            bitmap = rep
        } else if let tiffData = pasteboard.data(forType: .tiff), let rep = NSBitmapImageRep(data: tiffData) {
            // The re-encode allocates a full image-sized buffer; pool it
            // so the pages come back promptly instead of waiting for the
            // run loop's own autorelease pool to drain.
            guard let reencoded = autoreleasepool(invoking: { rep.representation(using: .png, properties: [:]) }) else {
                return nil
            }
            png = reencoded
            bitmap = rep
        } else {
            return nil
        }

        guard png.count <= ClipboardHistory.maxItemBytes else { return nil }

        let pixelSize = CGSize(width: bitmap.pixelsWide, height: bitmap.pixelsHigh)
        return ClipboardItem.image(png: png, pixelSize: pixelSize, copiedAt: now)
    }

    /// No image flavor: fall back to plain text plus whichever rich
    /// flavors are present. No `.string` data at all, or an empty string
    /// — a blank, unselectable history row helps nobody — is unsupported.
    private func readText(now: Date) -> ClipboardItem? {
        guard let plain = pasteboard.string(forType: .string), !plain.isEmpty else { return nil }
        guard plain.utf8.count <= ClipboardHistory.maxItemBytes else { return nil }

        return ClipboardItem.text(
            plain: plain,
            rtf: pasteboard.data(forType: .rtf),
            html: pasteboard.data(forType: .html),
            copiedAt: now
        )
    }

    // MARK: Writing

    private func writeText(plain: String, rtf: Data?, html: Data?, withFormatting: Bool) {
        pasteboard.setString(plain, forType: .string)
        guard withFormatting else { return }
        if let rtf {
            pasteboard.setData(rtf, forType: .rtf)
        }
        if let html {
            pasteboard.setData(html, forType: .html)
        }
    }

    /// Always writes PNG. Adds a TIFF representation too, but only when
    /// the image is small enough that the transient uncompressed buffer
    /// is cheap — same rule `ImageStore` applies to its own clipboard
    /// writes. Pixel size comes from the bitmap decoded to build that
    /// representation, so there's no separate size to pass in.
    private func writeImage(png: Data) {
        pasteboard.setData(png, forType: .png)

        guard let bitmap = NSBitmapImageRep(data: png) else { return }
        let pixelCount = bitmap.pixelsWide * bitmap.pixelsHigh
        guard pixelCount <= ImageStore.defaultClipboardTIFFMaxPixels else { return }

        // Same pooling reason as the read side: representation(using:)
        // hands back a full image-sized buffer.
        guard let tiff = autoreleasepool(invoking: { bitmap.representation(using: .tiff, properties: [:]) }) else { return }
        pasteboard.setData(tiff, forType: .tiff)
    }
}

// MARK: - CGEventKeystrokeSender

/// Synthesizes a Cmd+V key event pair so the item just written to the
/// pasteboard gets pasted into whatever app is focused. Accessibility
/// permission covers this; the app already requires it elsewhere.
final class CGEventKeystrokeSender: KeystrokeSending {
    /// kVK_ANSI_V.
    private static let vKeyCode: CGKeyCode = 0x09

    func sendPasteKeystroke() {
        guard let keyDown = CGEvent(keyboardEventSource: nil, virtualKey: Self.vKeyCode, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: nil, virtualKey: Self.vKeyCode, keyDown: false) else { return }

        // Set flags to exactly .maskCommand so modifier keys the user is
        // still physically holding don't leak into the synthesized paste.
        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand

        keyDown.post(tap: .cghidEventTap)
        keyUp.post(tap: .cghidEventTap)
    }
}
